export const ADD_CHARACTER = 'ADD_CHARACTER'
export const ADD_FAVORITE = 'ADD_FAVORITE';
export const REMOVE_FAVORITE ='REMOVE_FAVORITE';
export const DELETE_CHARAPTERS = 'DELETE_CHARAPTERS'
export const GET_CHARAPTERS_DETAILS = 'GET_CHARAPTERS_DETAILS'
export const GET_ALL_CHARACTERS = 'GET_ALL_CHARACTERS'
